In [2]:
import torch
scalar=torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [21]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [22]:
MATRIX.ndim

2

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

In [28]:
random_tensor=torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.3251, 0.9080, 0.6507, 0.7097],
         [0.9551, 0.3137, 0.8397, 0.1731],
         [0.9768, 0.3030, 0.2375, 0.8405]]),
 torch.float32)

In [29]:
random_image_size_tensor=torch.rand(size=(244,244,3))
random_image_size_tensor,random_image_size_tensor.shape,random_image_size_tensor.ndim

(tensor([[[1.1283e-01, 3.3172e-01, 5.7469e-01],
          [1.6755e-01, 3.4229e-01, 9.0844e-01],
          [2.3418e-01, 1.5902e-01, 5.1694e-01],
          ...,
          [1.1887e-01, 5.7814e-02, 1.1994e-02],
          [4.9638e-02, 9.8684e-01, 7.9873e-01],
          [2.2831e-01, 7.4922e-02, 1.3990e-01]],
 
         [[7.6445e-01, 7.1138e-01, 6.2745e-01],
          [1.8537e-04, 7.5640e-01, 7.3094e-01],
          [5.8854e-01, 8.5664e-01, 6.3064e-01],
          ...,
          [8.8803e-01, 9.6262e-01, 6.1648e-02],
          [3.7371e-01, 5.2723e-01, 1.4938e-01],
          [3.9175e-01, 2.6037e-01, 1.0201e-01]],
 
         [[7.2548e-01, 8.4819e-01, 7.2785e-01],
          [8.1242e-01, 3.6650e-01, 3.9623e-01],
          [8.1689e-01, 4.1567e-01, 6.3044e-01],
          ...,
          [5.9421e-01, 2.0717e-01, 3.6686e-01],
          [1.7238e-01, 7.4460e-01, 2.7798e-01],
          [3.5893e-01, 6.5145e-01, 7.1598e-01]],
 
         ...,
 
         [[1.2123e-01, 1.7172e-01, 1.0079e-01],
          [9.9026e

In [31]:
zeros=torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [32]:
ones=torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [33]:
zero_to_ten=torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
ten_zeros=torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
float_32_tensor=torch.zeros(size=(3,4),dtype=torch.float32)
float_32_tensor,float_32_tensor.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [38]:
float_16_tensor=torch.zeros(size=(3,4),dtype=torch.float16)
float_16_tensor,float_16_tensor.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]], dtype=torch.float16),
 torch.float16)

In [39]:
some_tensor=torch.rand(3,4)

In [40]:
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Type of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.3067, 0.9422, 0.6273, 0.5846],
        [0.3869, 0.8263, 0.8387, 0.4073],
        [0.0888, 0.5447, 0.7505, 0.0403]])
Shape of tensor: torch.Size([3, 4])
Type of tensor: torch.float32
Device tensor is stored on: cpu


In [47]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [48]:
tensor*10

tensor([10, 20, 30])

In [49]:
tensor

tensor([1, 2, 3])

In [50]:
tensor-=10
tensor

tensor([-9, -8, -7])

In [51]:
tensor+=10
tensor

tensor([1, 2, 3])

In [52]:
tensor.shape

torch.Size([3])

In [53]:
tensor*tensor

tensor([1, 4, 9])

In [54]:
torch.matmul(tensor,tensor)

tensor(14)

In [63]:
tensor@tensor

tensor(14)

In [56]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.63 ms, sys: 0 ns, total: 2.63 ms
Wall time: 1.96 ms


tensor(14)

In [57]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 897 μs, sys: 258 μs, total: 1.15 ms
Wall time: 769 μs


tensor(14)

In [61]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

tensor_A@ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [64]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [65]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [68]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [69]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [70]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [74]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape,x,x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([1, 7]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.Size([7]))

In [84]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [87]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [88]:
# Create a tensor 
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [89]:
x[:,:,1]

tensor([[2, 5, 8]])

In [90]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
!nvidia-smi

Tue Aug 27 23:04:31 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.76.01              Driver Version: 552.44         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   59C    P8              9W /   95W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [92]:
torch.cuda.is_available()

True

In [93]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [94]:
torch.cuda.device_count()

1

In [95]:
tensor=torch.tensor([1,2,3])
# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [96]:
# Move tensor to GPU
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [97]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [98]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [99]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')