# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
tensor=torch.rand(7,7)
tensor

tensor([[0.6076, 0.6842, 0.8282, 0.6995, 0.3158, 0.7982, 0.6283],
        [0.7891, 0.0596, 0.5014, 0.4954, 0.0984, 0.6465, 0.8063],
        [0.9365, 0.5460, 0.0783, 0.3169, 0.3702, 0.6459, 0.1835],
        [0.8615, 0.6083, 0.8323, 0.0058, 0.3327, 0.2072, 0.2689],
        [0.1499, 0.8133, 0.1378, 0.9187, 0.1288, 0.3278, 0.2079],
        [0.2053, 0.9967, 0.3093, 0.2754, 0.1774, 0.7864, 0.7272],
        [0.1735, 0.7392, 0.9519, 0.8555, 0.3535, 0.5677, 0.4119]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
tensor2=torch.rand(1,7)

# Perform matrix multiplication 
tensor@tensor2.T


tensor([[1.1305],
        [0.6920],
        [0.6093],
        [0.6285],
        [0.9141],
        [0.8003],
        [1.2132]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
torch.manual_seed(42)

# Create two random tensors
a=torch.rand(7,7)
b=torch.rand(1,7)

# Matrix multiply tensors
a*b.T

tensor([[1.7226e-01, 1.7865e-01, 7.4753e-02, 1.8730e-01, 7.6234e-02, 1.1732e-01,
         5.0095e-02],
        [4.0045e-03, 4.7469e-03, 6.7203e-04, 4.7158e-03, 2.9951e-03, 4.3868e-03,
         2.8646e-03],
        [2.2738e-01, 1.3175e-01, 2.7167e-01, 1.7609e-01, 8.1792e-02, 1.9251e-01,
         8.2728e-02],
        [5.1414e-02, 3.4588e-02, 9.6882e-02, 1.2268e-02, 3.1393e-02, 4.1798e-02,
         2.3224e-02],
        [4.9809e-01, 5.6077e-03, 8.6617e-01, 6.8512e-02, 8.0651e-01, 5.3088e-01,
         3.0735e-01],
        [5.2099e-01, 3.7219e-01, 5.8218e-01, 3.5721e-01, 2.2046e-01, 4.0853e-01,
         2.3469e-01],
        [5.0235e-01, 6.6921e-01, 5.5793e-01, 1.9899e-01, 5.5765e-01, 4.1681e-01,
         5.3310e-01]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(134)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.cuda.manual_seed(134)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
c=torch.rand(3,4).to(device)
d=torch.rand(3,4).to(device)



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
e=c@d.T

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
e.max(),e.min()
# Find min



(tensor(1.7470, device='cuda:0'), tensor(0.2007, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
e.argmax(),e.argmin()

# Find arg min


(tensor(8, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(10)

# Create random tensor
tensor=torch.rand(1,1,1,10)

# Remove single dimensions
removed=tensor.squeeze()

# Print out tensors and their shapes
removed,removed.shape

(tensor([0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693, 0.6178,
         0.3304]),
 torch.Size([10]))